### ISSUE TITLE
Incorrect Almanax XP

### ISSUE THREAD

**Issue by Skrys33** [GanymedeTeam/GanymedeApp#32]
The theoretically earned XP shown in the Almanax panel is incorrect.

**Comment by Pynx** [comment]
Hello, can you give us more details ? We're using the information we get from the E-BOU discord bot.

Are we not taking the right value or is it the bot giving wrong data ?

**Comment by Skrys33** [comment]
I have no idea why. I just notice a difference. 

![image](https://github.com/user-attachments/assets/3d33f469-507c-477c-9cd7-4816a7de7c74)

**Comment by mouahahaaa** [comment]
Hey @Skrys33 ,
We investigated and according to E-bou bot owner, it is due to Ankama Shield 5% bonus XP.

**Comment by Skrys33** [comment]
Indeed, you are right. Thank you !
