### ISSUE TITLE
New guide class

### ISSUE THREAD

**Issue by Pynx** [GanymedeTeam/GanymedeApp#5]
The actual class to save guide will be outdated, we need a way to "Load" OLD AND NEW json

Details : 

- We should still be able to read our old JSON
- Implement new JSON structure with more than one substep into each step

Description

( Sorry for how it looks here, copy it into your IDE for more clarity :( )

Previous JSON structure
`{
    "Items": [
    {
        "ID": "1",
        "map": "Incarnam",
        "travelPosition": "0,0",
        "title": "Titre",
        "description": "Step description"
    },
    {
        "ID": "2",
        "map": "Incarnam",
        "travelPosition": "0,0",
        "title": "Titre 2",
        "description": "Step Description 2"
    }
]}`

Probable new JSON structure

`{
    "id": 1,
    "user_id": 1,
    "name": "Example Guide",
    "status": "validated",
    "description": "Guide servant d'exemple",
    "created_at": "2024-05-28T21:15:59.000000Z",
    "updated_at": "2024-05-29T11:59:37.000000Z",
    "deleted_at": null,
    "steps": [
        {
            "id": 1,
            "route_id": 1,
            "name": "Début du guide",
            "order": 1,
            "created_at": "2024-05-28T21:20:59.000000Z",
            "updated_at": "2024-05-29T11:39:41.000000Z",
            "deleted_at": null,
            "sub_steps": [
                {
                    "id": 1,
                    "type": "TEXT",
                    "step_id": 1,
                    "order": 1,
                    "text": "Bienvenue dans ce guide. Il a pour but de vous permettre de faire votre aventure complète sans perdre de temps.\\n\\nAu fur et à mesure des étapes, vous verrez les informations importantes <color=#ffff00>en jaune</color> et la position de la prochaine étape à la fin de la description <color=#62ACFF>en bleu</color>\r\nPar moment le guide vous demandera de mettre de coté des ressources. Elles seront utilisées plus tard dans des quêtes, libre à vous de les vendre à la place, mais vous risquez de devoir les drop à nouveau plus tard\r\nSi vous voyez la moindre erreur, n hésitez pas à me le dire ( <color=#ffff00>pynx_</color> sur discord ) en fournissant l étape à laquelle vous êtes",
                    "content_id": null,
                    "content_type": null,
                    "created_at": "2024-05-28T21:32:50.000000Z",
                    "updated_at": "2024-05-29T11:40:44.000000Z",
                    "deleted_at": null,
                    "items": [],
                    "content": null
                },
                {
                    "id": 15,
                    "type": "TEXT",
                    "step_id": 1,
                    "order": 3,
                    "text": "Parlez au <color=#ffff00>Capitaine des Kerubims</color> pour <color=#ffff00>annoncer votre victoire</color> et valider la quête <color=#ffff00>Mise à l'épreuve</color>\\n\\n- Reparlez lui ensuite pour débuter la quête <color=#ffff00>Champs de bataille</color>\\n\\n- sortez ensuite puis allez <color=#62ACFF>1 map en bas et 1 à gauche</color>",
                    "content_id": null,
                    "content_type": null,
                    "created_at": "2024-05-29T15:32:06.000000Z",
                    "updated_at": "2024-05-29T15:32:06.000000Z",
                    "deleted_at": null,
                    "items": [],
                    "content": null
                }
            ]
        },
        {
            "id": 2,
            "route_id": 1,
            "name": "Tuto Incarnam",
            "order": 2,
            "created_at": "2024-05-29T11:44:11.000000Z",
            "updated_at": "2024-05-29T11:44:11.000000Z",
            "deleted_at": null,
            "sub_steps": [
                {
                    "id": 2,
                    "type": "TEXT",
                    "step_id": 2,
                    "order": 1,
                    "text": "Terminez le tutoriel de <color=#ffff00>Ganymède</color> complètement jusqu'a sortir du temple devant <color=#ffff00>Lykhen Lesurviven</color>",
                    "content_id": null,
                    "content_type": null,
                    "created_at": "2024-05-29T11:44:40.000000Z",
                    "updated_at": "2024-05-29T11:44:40.000000Z",
                    "deleted_at": null,
                    "items": [],
                    "content": null
                }
            ]
        }
    ]
}`

**Comment by pray-mess** [comment]
```json

{
   "id":1,
   "user_id":1,
   "name":"Example Guide",
   "status":"validated",
   "description":"Guide servant d'exemple",
   "created_at":"2024-05-28T21:15:59.000000Z",
   "updated_at":"2024-05-29T11:59:37.000000Z",
   "deleted_at":null,
   "steps":[
      {
         "id":1,
         "route_id":1,
         "name":"Début du guide",
         "order":1,
         "created_at":"2024-05-28T21:20:59.000000Z",
         "updated_at":"2024-05-29T11:39:41.000000Z",
         "deleted_at":null,
         "sub_steps":[
            {
               "id":1,
               "type":"TEXT",
               "step_id":1,
               "order":1,
               "text":"Bienvenue dans ce guide. Il a pour but de vous permettre de faire votre aventure complète sans perdre de temps.\\n\\nAu fur et à mesure des étapes, vous verrez les informations importantes <color=#ffff00>en jaune</color> et la position de la prochaine étape à la fin de la description <color=#62ACFF>en bleu</color>\r\nPar moment le guide vous demandera de mettre de coté des ressources. Elles seront utilisées plus tard dans des quêtes, libre à vous de les vendre à la place, mais vous risquez de devoir les drop à nouveau plus tard\r\nSi vous voyez la moindre erreur, n hésitez pas à me le dire ( <color=#ffff00>pynx_</color> sur discord ) en fournissant l étape à laquelle vous êtes",
               "content_id":null,
               "content_type":null,
               "created_at":"2024-05-28T21:32:50.000000Z",
               "updated_at":"2024-05-29T11:40:44.000000Z",
               "deleted_at":null,
               "items":[
                  
               ],
               "content":null
            },
            {
               "id":15,
               "type":"TEXT",
               "step_id":1,
               "order":3,
               "text":"Parlez au <color=#ffff00>Capitaine des Kerubims</color> pour <color=#ffff00>annoncer votre victoire</color> et valider la quête <color=#ffff00>Mise à l'épreuve</color>\\n\\n- Reparlez lui ensuite pour débuter la quête <color=#ffff00>Champs de bataille</color>\\n\\n- sortez ensuite puis allez <color=#62ACFF>1 map en bas et 1 à gauche</color>",
               "content_id":null,
               "content_type":null,
               "created_at":"2024-05-29T15:32:06.000000Z",
               "updated_at":"2024-05-29T15:32:06.000000Z",
               "deleted_at":null,
               "items":[
                  
               ],
               "content":null
            }
         ]
      },
      {
         "id":2,
         "route_id":1,
         "name":"Tuto Incarnam",
         "order":2,
         "created_at":"2024-05-29T11:44:11.000000Z",
         "updated_at":"2024-05-29T11:44:11.000000Z",
         "deleted_at":null,
         "sub_steps":[
            {
               "id":2,
               "type":"TEXT",
               "step_id":2,
               "order":1,
               "text":"Terminez le tutoriel de <color=#ffff00>Ganymède</color> complètement jusqu'a sortir du temple devant <color=#ffff00>Lykhen Lesurviven</color>",
               "content_id":null,
               "content_type":null,
               "created_at":"2024-05-29T11:44:40.000000Z",
               "updated_at":"2024-05-29T11:44:40.000000Z",
               "deleted_at":null,
               "items":[
                  
               ],
               "content":null
            }
         ]
      }
   ]
}
```
